server:
  port: ${AGENT_PORT:8081}

app:
  role: agent
  agent:
    id: ${AGENT_ID:AGENT1}
    name: ${AGENT_NAME:Default Agent}
  master:
    url: ${MASTER_URL:http://localhost:8080}
  sync:
    enabled: true
    interval: 30000  # 30 seconds

spring:
  kafka:
    producer:
      acks: all     # Wait for all replicas (safety)
      retires: 3
